-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Sep 26, 2023 at 10:22 AM
-- Server version: 5.7.39-42-log
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbbfs4gyepnucr`
--

-- --------------------------------------------------------

--
-- Table structure for table `single_pages`
--

CREATE TABLE `single_pages` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `page_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `frontend_slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `form_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `documentation` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `saved_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `single_pages`
--

INSERT INTO `single_pages` (`id`, `page_key`, `frontend_slug`, `title`, `form_data`, `documentation`, `saved_data`, `created_at`, `updated_at`, `deleted_at`, `created_by`, `updated_by`, `deleted_by`) VALUES
(1, 'icsb-profile', 'icsb-profile', 'ICSB Profile', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"back-image\", \"field_name\": \"Back Image\"}, \"3\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"front-image\", \"field_name\": \"Front Image\"}, \"4\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}}', '{\"title\": \"ICSB Profile\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(2, 'mission', 'mission', 'Mission', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}}', '{\"title\": \"Mission\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(3, 'objectives', 'objectives', 'Objectives', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}}', '{\"title\": \"Objectives\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(4, 'values', 'values', 'Values', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"Values\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(5, 'cs-for-cg', 'cs-for-cg', 'CS for CG', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}, \"5\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}}', '{\"title\": \"CS for CG\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(6, 'corporate-governance', 'corporate-governance', 'Corporate Governance', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}, \"5\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}}', '{\"title\": \"Corporate Governance\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(7, 'who-are-css', 'who-are-css', 'Who are CSs', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"Who are CSs\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(8, 'cs-membership', 'cs-membership', 'CS Membership', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"CS Membership\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(9, 'code-of-conducts', 'code-of-conducts', 'Code of Conducts', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}}', '{\"title\": \"Code of Conducts\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(10, 'cpd-program', 'cpd-program', 'CPD Program', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"CPD Program\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}', '{\"page-image\":\"single-page\\/image-single\\/page-image\\/1695061865.jpg\",\"page-description\":\"<p style=\\\"text-align:justify;\\\">The Institute is committed to supporting the CS as a lifelong governance professional by offering regular CPD programs in various formats, such as workshops, seminars, conferences, and discussion sessions.<\\/p><p style=\\\"text-align:justify;\\\">Every member who has completed all Certificate and Professional Levels examinations of the Institute and a Case Study is required to fulfill the mandatory hours of Continuing Professional Development (CPD) as specified by the Institute from time to time.<\\/p>\"}', '2023-08-09 04:08:03', '2023-09-18 18:31:05', NULL, NULL, NULL, NULL),
(11, 'member-portal', 'member-portal', 'Member Portal', '{\"1\": {\"type\": \"url\", \"required\": \"required\", \"field_key\": \"portal-url\", \"field_name\": \"Portal Url\"}}', '{\"title\": \"Member Portal\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}', '{\"portal-url\": \"https://icsberp.org/users/login.aspx\"}', '2023-08-09 04:12:21', '2023-08-09 04:12:44', NULL, NULL, NULL, NULL),
(12, 'training-program', 'training-program', 'Training Program', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"Training Program\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(14, 'cs-hand-book', 'cs-hand-book', 'CS Hand Book', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"new-student-hand-book-pdf\", \"field_name\": \"New Student Hand Book PDF\"}, \"3\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"old-student-hand-book-pdf\", \"field_name\": \"Old Student Hand Book PDF\"}}', '{\"title\": \"CS Hand Book\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(15, 'student-portal', 'student-portal', 'Student Portal', '{\"1\": {\"type\": \"url\", \"required\": \"required\", \"field_key\": \"portal-url\", \"field_name\": \"Portal Url\"}}', '{\"title\": \"Student Portal\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(17, 'faculty-evaluation-system', 'faculty-evaluation-system', 'Faculty Evaluation System', '{\"1\": {\"type\": \"url\", \"required\": \"required\", \"field_key\": \"url\", \"field_name\": \"URL\"}}', '{\"title\": \"Faculty Evaluation System\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(18, 'help-desk', 'help-desk', 'Help Desk', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}}', '{\"title\": \"Help Desk\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(19, 'cs-practicing-guideline', 'cs-practicing-guideline', 'CS Practicing Guideline', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_multiple\", \"required\": \"nullable\", \"field_key\": \"upload-files\", \"field_name\": \"Upload Files\"}}', '{\"title\": \"CS Practicing Guideline\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(20, 'others', 'others', 'Others', '{\"1\": {\"type\": \"url\", \"required\": \"required\", \"field_key\": \"url\", \"field_name\": \"URL\"}}', '{\"title\": \"Others\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(21, 'eligibility', 'eligibility', 'Eligibility', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload File\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"Eligibility\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(22, 'vision', 'vision', 'Vision', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}}', '{\"title\": \"Vision\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(23, 'exam-schedule', 'exam-schedule', 'Exam Schedule', '{\"1\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"banner-image\", \"field_name\": \"Banner Image\"}, \"2\": {\"type\": \"image\", \"required\": \"nullable\", \"field_key\": \"page-image\", \"field_name\": \"Page Image\"}, \"3\": {\"type\": \"textarea\", \"required\": \"required\", \"field_key\": \"page-description\", \"field_name\": \"Page Description\"}, \"4\": {\"type\": \"file_single\", \"required\": \"nullable\", \"field_key\": \"upload-file\", \"field_name\": \"Upload FIle\"}, \"5\": {\"type\": \"image_multipe\", \"required\": \"nullable\", \"field_key\": \"upload-images\", \"field_name\": \"Upload Images\"}}', '{\"title\": \"Exam Schedule\", \"details\": \"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.</span></p>\"}',
(25, 'csr-initiatives', 'csr-initiatives', 'CSR Initiatives', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"},\"4\":{\"field_key\":\"upload-file\",\"field_name\":\"Upload File\",\"type\":\"file_single\",\"required\":\"nullable\"}}', '{\"title\":\"CSR Initiatives\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
INSERT INTO `single_pages` (`id`, `page_key`, `frontend_slug`, `title`, `form_data`, `documentation`, `saved_data`, `created_at`, `updated_at`, `deleted_at`, `created_by`, `updated_by`, `deleted_by`) VALUES
(26, 'membership-benefits', 'membership-benefits', 'Membership Benefits', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"},\"4\":{\"field_key\":\"upload-file\",\"field_name\":\"Upload File\",\"type\":\"file_single\",\"required\":\"nullable\"}}', '{\"title\":\"Membership Benefits\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(27, 'the-chartered-secretary', 'the-chartered-secretary', 'The Chartered Secretary', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"The Chartered Secretary\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(28, 'admission-form', 'admission-form', 'Admission Form', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Admission Form\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(29, 'entry-criteria', 'entry-criteria', 'Entry Criteria', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Entry Criteria\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(30, 'examination-policy', 'examination-policy', 'Examination Policy', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Examination Policy\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(33, 'financial-assistance', 'financial-assistance', 'Financial Assistance', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"required\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"required\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Financial Assistance\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(34, 'annual-report', 'annual-report', 'Annual Report', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Annual Report\",\"details\":\"<p style=\\\"margin-left:-15px;\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/p>\"}',
(35, 'members-lounge', 'members-lounge', 'Members Lounge', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-images\",\"field_name\":\"Page Images\",\"type\":\"image_multiple\",\"required\":\"required\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Members Lounge\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(36, 'icsb-library', 'icsb-library', 'ICSB Library', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-images\",\"field_name\":\"Page Images\",\"type\":\"image_multiple\",\"required\":\"required\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"ICSB Library\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(37, 'foundation-complete', 'foundation-complete', 'Foundation Complete', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Foundation Complete\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(38, 'subject-complete', 'subject-complete', 'Subject Complete', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Subject Complete\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(39, 'final-complete', 'final-complete', 'Final Complete', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Final Complete\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(40, 'genesis', 'genesis', 'Genesis', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Genesis\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(41, 'purpose-of-the-award', 'purpose-of-the-award', 'Purpose of the Award', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Purpose of the Award\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(42, 'eligibility-for-participation', 'eligibility-for-participation', 'Eligibility for Participation', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Eligibility for Participation\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(43, 'sources-for-evaluation', 'sources-for-evaluation', 'Sources for Evaluation', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Sources for Evaluation\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(44, 'evaluation-&-assessment-basis', 'evaluation-&-assessment-basis', 'Evaluation & Assessment Basis', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Evaluation & Assessment Basis\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(45, 'jury-board', 'jury-board', 'Jury Board', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Jury Board\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(46, 'assessment-criteria', 'assessment-criteria', 'Assessment Criteria', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Assessment Criteria\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(47, 'fees-&-costs', 'fees-&-costs', 'Fees & Costs', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"upload-files\",\"field_name\":\"Upload Files\",\"type\":\"file_multiple\",\"required\":\"required\"}}', '{\"title\":\"Fees & Costs\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(48, 'icsb-faculty', 'icsb-faculty', 'ICSB Faculty', '{\"1\":{\"field_key\":\"banner-image\",\"field_name\":\"Banner Image\",\"type\":\"image\",\"required\":\"nullable\"},\"2\":{\"field_key\":\"page-image\",\"field_name\":\"Page Image\",\"type\":\"image\",\"required\":\"nullable\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"ICSB Faculty\",\"details\":\"<p style=\\\"margin-left:-15px;\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/p><p style=\\\"margin-left:auto;\\\"><br>&nbsp;<\\/p>\"}',
(49, 'who-we-are', 'who-we-are', 'Who we are', '{\"1\":{\"field_key\":\"background-image\",\"field_name\":\"Background Image\",\"type\":\"image\",\"required\":\"required\"},\"2\":{\"field_key\":\"slider-images\",\"field_name\":\"Slider Images\",\"type\":\"image_multiple\",\"required\":\"required\"},\"3\":{\"field_key\":\"page-description\",\"field_name\":\"Page Description\",\"type\":\"textarea\",\"required\":\"required\"}}', '{\"title\":\"Who we are\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',
(50, 'pop-up', 'pop-up', 'Pop Up', '{\"1\":{\"field_key\":\"upload-image\",\"field_name\":\"Upload Image\",\"type\":\"image\",\"required\":\"required\"}}', '{\"title\":\"Pop Up\",\"details\":\"<p><span style=\\\"background-color:rgb(255,255,255);color:rgb(29,37,59);\\\">The role\'s manages user permissions by assigning different roles to users. Each role defines specific access levels and actions a user can perform. It helps ensure proper authorization and security in the system.<\\/span><\\/p>\"}',

--
-- Indexes for dumped tables
--

--
-- Indexes for table `single_pages`
--
ALTER TABLE `single_pages`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `single_pages_page_key_unique` (`page_key`),
  ADD UNIQUE KEY `single_pages_frontend_slug_unique` (`frontend_slug`),
  ADD KEY `single_pages_created_by_foreign` (`created_by`),
  ADD KEY `single_pages_updated_by_foreign` (`updated_by`),
  ADD KEY `single_pages_deleted_by_foreign` (`deleted_by`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `single_pages`
--
ALTER TABLE `single_pages`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `single_pages`
--
ALTER TABLE `single_pages`
  ADD CONSTRAINT `single_pages_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `single_pages_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `single_pages_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
